"""empty message

Revision ID: db6cb1a43b43
Revises: dabbf3e912b6
Create Date: 2022-07-06 12:06:56.596101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6cb1a43b43'
down_revision = 'dabbf3e912b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('administered', sa.Integer(), nullable=True),
    sa.Column('people_vaccinated', sa.Integer(), nullable=True),
    sa.Column('people_partially_vaccinated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    # ### end Alembic commands ###
